image:
  repository: kong/kong-gateway
  tag: "2.8.4.8" 

migrations:
  preUpgrade: false
  postUpgrade: false
  annotations:
    sidecar.istio.io/inject: false
    kuma.io/sidecar-injection: "disabled"

updateStrategy: {}

extraLabels:
  kong_type: cp

waitImage:
  pullPolicy: IfNotPresent

postgresql:
  enabled: true
  primary:
    service:
      type: LoadBalancer
      ports:
        postgresql: 5432
    persistence:
      enabled: false
  postgresqlUsername: kong
  postgresqlDatabase: kong
  auth:
    existingSecret: postgresql-password

env:
  # Kong role
  role: control_plane
  # datastore config
  database: "postgres"
  pg_host: kong-cp-postgresql
  pg_user: kong
  pg_database: kong
  pg_password: kong
  password:
    valueFrom:
      secretKeyRef:
        name: kong-enterprise-superuser-password
        key: password

  # url callbacks
  admin_api_uri: http://48.217.15.251:8001

  # clustering certificates
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  log_level: debug
  admin_gui_access_log: /kong_prefix/admin_gui_access.log
  admin_gui_error_log: /kong_prefix/admin_gui_error.log
  admin_access_log: /kong_prefix/admin_access.log
  admin_error_log: /kong_prefix/admin_error.log

  nginx_http_client_max_body_size: 1m

  # plugins: bundled, myplugin, kplugin
  # plugins: bundled, plugintemplate, plugintemplate2, plugintemplate3
  # plugins: bundled

secretVolumes:
  - kong-cluster-cert

# plugins:
#   configMaps:
#   - name: plugintemplate
#     pluginName: plugintemplate
#   - name: plugintemplate2
#     pluginName: plugintemplate2
#   - name: plugintemplate3
#     pluginName: plugintemplate3

admin:
  enabled: true
  type: LoadBalancer
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001
    parameters: []

  tls:
    # Enable HTTPS listen for the admin API
    enabled: true
    servicePort: 8444
    containerPort: 8444
    parameters:
    - http2

# Kong manager configuration settings
manager:
  enabled: true
  type: LoadBalancer 
  http:
    enabled: true
    servicePort: 8002
    containerPort: 8002
    parameters: []

  tls:
    # Enable HTTPS listen for Kong Manager
    enabled: true
    servicePort: 8445
    containerPort: 8445
    parameters:
    - http2

# Kong cluster endpoint settings 
cluster:
  enabled: true
  type: ClusterIP

  tls:
    enabled: true
    servicePort: 8005
    containerPort: 8005
    parameters: []

# Kong telemetry endpoint settings 
clustertelemetry:
  enabled: true
  type: ClusterIP

  tls:
    enabled: true
    servicePort: 8006
    containerPort: 8006
    parameters: []

# Kong portal configuration settings
portal:
  enabled: true
  type: LoadBalancer
  http:
    enabled: true
    servicePort: 8003
    containerPort: 8003
    parameters: []

  tls:
    # Enable HTTPS listen for the admin API
    enabled: true
    servicePort: 8446
    containerPort: 8446
    parameters:
    - http2

# Kong portal api configuration settings
portalapi:
  enabled: true
  type: LoadBalancer
  http:
    enabled: true
    servicePort: 8004
    containerPort: 8004
    parameters: []

  tls:
    # Enable HTTPS listen for the admin API
    enabled: true
    servicePort: 8447
    containerPort: 8447
    parameters:
    - http2

ingressController:
  enabled: false

proxy:
  enabled: false

status:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    containerPort: 8100

enterprise:
  enabled: true
  license_secret: kong-enterprise-license
  vitals:
    enabled: true
  portal:
    enabled: false
  rbac:
    enabled: false
    admin_gui_auth: basic-auth
    session_conf_secret: kong-session-config

resources: {}
