image:
  repository: kong/kong-gateway
  tag: "3.4.0.0"

waitImage:
  pullPolicy: IfNotPresent

extraLabels:
  kong_type: dp

env:
  database: "off"
  prefix: /kong_prefix/
  cluster_control_plane: kong-cp-kong-cluster.kong.svc.cluster.local:8005
  cluster_telemetry_endpoint: kong-cp-kong-clustertelemetry.kong.svc.cluster.local:8006
  lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  log_level: debug
  role: data_plane
  nginx_http_client_max_body_size: 1m
  plugins: bundled, plugintemplate, plugintemplate2, plugintemplate3
  # plugins: bundled

secretVolumes:
  - kong-cluster-cert

plugins:
  configMaps:
  - name: plugintemplate
    pluginName: plugintemplate
  - name: plugintemplate2
    pluginName: plugintemplate2
  - name: plugintemplate3
    pluginName: plugintemplate3

admin:
  enabled: false 

manager:
  enabled: false

portal:
  enabled: false

portalapi:
  enabled: false

cluster:
  enabled: false

clustertelemetry:
  enabled: false

ingressController:
  enabled: false

proxy:
  enabled: true
  type: LoadBalancer
  http:
    enabled: true
    servicePort: 8000
    containerPort: 8000

  tls:
    enabled: false
    servicePort: 8447
    containerPort: 8447
    parameters:
      - http2

status:
  enabled: true
  type: ClusterIP

  http:
    enabled: true
    containerPort: 8100

enterprise:
  enabled: true
  license_secret: kong-enterprise-license
  vitals:
    enabled: true

resources:
  limits:
    cpu: "2"
    memory: "2G"
  requests:
    cpu: "0.5"
    memory: "1G"
